name: qhjack phpuni

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git Clone this repo
      uses: actions/checkout@v2.3.4
      with:
        submodules: true
    
    - name: Setup PHP 7.4
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.4
  
    - name: Setup Mariadb
      uses: getong/mariadb-action@v1.1
      with:
        mysql database: wptest
        mysql user: wptest
        mysql password: wptest
    
    - name: PHP Composer
      run: |
        ./composer.phar install

    - name: Pre Test
      run: |
        mkdir -p tests/code_coverage/
    
    - name: Test
      run: |
        php vendor/bin/phpunit 
