name: qhjack phpuni

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git Clone this repo
      uses: actions/checkout@v2.3.4
      with:
        submodules: true
    
    - name: Setup PHP 7.4
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.4
  
    - name: Setup Mariadb
      run: |
        curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
        sudo apt update
        sudo apt-get install -y mariadb-server-10.5
        sudo systemctl start mariadb
        sudo mysql -uroot -proot -e 'create database wptest;'
        sudo mysql -uroot -proot -e "CREATE USER 'wptest'@'%' IDENTIFIED BY 'wptest';"
        sudo mysql -uroot -proot -e "GRANT ALL ON wptest.* TO 'wptest'@'%';"
    
    - name: PHP Composer
      run: |
        ./composer.phar install

    - name: Pre Test
      run: |
        mkdir -p tests/code_coverage/
    
    - name: Test
      run: |
        php vendor/bin/phpunit 
