name: qhjack deploy

on:
  push:
    tags:
        - 'v*.*'

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git Clone this repo
      uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: Setup PHP 7.4
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.4
  
    - name: Setup Mariadb
      run: |
        curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
        sudo apt update
        sudo apt-get install -y mariadb-server-10.5
        sudo systemctl start mariadb
        sudo mysql -uroot -proot -e 'create database wptest;'
        sudo mysql -uroot -proot -e "CREATE USER 'wptest'@'%' IDENTIFIED BY 'wptest';"
        sudo mysql -uroot -proot -e "GRANT ALL ON wptest.* TO 'wptest'@'%';"
    
    - name: PHP Composer
      run: |
        ./composer.phar install

    - name: Pre Test
      run: |
        mkdir -p tests/code_coverage/
    
    - name: Test
      run: |
        php vendor/bin/phpunit
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
  
    steps:
    - name: Git Clone this repo
      uses: actions/checkout@v2.3.4

    - name: Clean Test data
      run: |
        rm -rf tests
        rm -f phpunit.xml
        rm -f composer.json
        rm -f composer.lock
        rm -f composer.phar
        rm -rf vendor
  
    - name: Upload Wordpress Server
      env:
        QHJACK_DEPLOY_SERVER_USERNAME: ${{ secrets.QHJACK_DEPLOY_SERVER_USERNAME }}
        QHJACK_DEPLOY_SERVER_PASSWORD: ${{ secrets.QHJACK_DEPLOY_SERVER_PASSWORD }}
        QHJACK_DEPLOY_SERVER_PUSH: ${{ secrets.QHJACK_DEPLOY_SERVER_PUSH }}
      run: |
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD scp -o StrictHostKeyChecking=no -r * $QHJACK_DEPLOY_SERVER_USERNAME@$QHJACK_DEPLOY_SERVER_PUSH:/glusterfs/webroot/qhjack/wp-content/themes/home/
    
    - name: Apply Deploy
      env:
        QHJACK_DEPLOY_SERVER_USERNAME: ${{ secrets.QHJACK_DEPLOY_SERVER_USERNAME }}
        QHJACK_DEPLOY_SERVER_PASSWORD: ${{ secrets.QHJACK_DEPLOY_SERVER_PASSWORD }}
        QHJACK_DEPLOY_SERVERS: ${{ secrets.QHJACK_DEPLOY_SERVERS }}
        QHJACK_DEPLOY_SERVER_PUSH: ${{ secrets.QHJACK_DEPLOY_SERVER_PUSH }}
        QHJACK_DEPLOY_SERVER_PROXY: ${{ secrets.QHJACK_DEPLOY_SERVER_PROXY }}
      run: |
        for service_addr in ${QHJACK_DEPLOY_SERVERS[@]}
        do
          sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@$service_addr -o StrictHostKeyChecking=no 'systemctl restart php-fpm && systemctl restart nginx'
        done
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@$QHJACK_DEPLOY_SERVER_PROXY -o StrictHostKeyChecking=no 'rm -rf "/www/services/nginx/cache/proxy/qhjack/*" && rm -rf "/www/services/nginx/cache/proxy_store/*"'
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@$QHJACK_DEPLOY_SERVER_PROXY -o StrictHostKeyChecking=no 'systemctl restart nginx'
    
