name: qhjack deploy

on:
  push:
    tags:
        - 'v*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git Clone this repo
      uses: actions/checkout@v2.3.4
  
    - name: Upload Wordpress Server
      env:
        QHJACK_DEPLOY_SERVER_USERNAME: ${{ secrets.QHJACK_DEPLOY_SERVER_USERNAME }}
        QHJACK_DEPLOY_SERVER_PASSWORD: ${{ secrets.QHJACK_DEPLOY_SERVER_PASSWORD }}
      run: |
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD scp -o StrictHostKeyChecking=no -r * $QHJACK_DEPLOY_SERVER_USERNAME@'service1.kvm.qhjack.cn':/glusterfs/webroot/qhjack/wp-content/themes/home/
    
    - name: Apply Deploy
      env:
        QHJACK_DEPLOY_SERVER_USERNAME: ${{ secrets.QHJACK_DEPLOY_SERVER_USERNAME }}
        QHJACK_DEPLOY_SERVER_PASSWORD: ${{ secrets.QHJACK_DEPLOY_SERVER_PASSWORD }}
      run: |
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@'service1.kvm.qhjack.cn' -o StrictHostKeyChecking=no 'systemctl restart php-fpm && systemctl restart nginx'
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@'service2.kvm.qhjack.cn' -o StrictHostKeyChecking=no 'systemctl restart php-fpm && systemctl restart nginx'
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@'service3.kvm.qhjack.cn' -o StrictHostKeyChecking=no 'systemctl restart php-fpm && systemctl restart nginx'
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@'service4.kvm.qhjack.cn' -o StrictHostKeyChecking=no 'rm -rf "/www/services/nginx/cache/proxy/qhjack/*" && rm -rf "/www/services/nginx/cache/proxy_store/*"'
        sshpass -p $QHJACK_DEPLOY_SERVER_PASSWORD ssh $QHJACK_DEPLOY_SERVER_USERNAME@'service4.kvm.qhjack.cn' -o StrictHostKeyChecking=no 'systemctl restart nginx'
    
